export const SUPPLIER_REGISTER_REQUEST = 'SUPPLIER_REGISTER_REQUEST'
export const SUPPLIER_REGISTER_SUCCESS = 'SUPPLIER_REGISTER_SUCCESS'
export const SUPPLIER_REGISTER_FAILURE = 'SUPPLIER_REGISTER_FAILURE'

export const SUPPLIER_LOGIN_REQUEST = 'SUPPLIER_LOGIN_REQUEST';
export const SUPPLIER_LOGIN_SUCCESS = 'SUPPLIER_LOGIN_SUCCESS';
export const SUPPLIER_LOGIN_FAILURE = 'SUPPLIER_LOGIN_FAILURE';

export const GET_SUPPLIER_REQUEST = 'GET_SUPPLIER_REQUEST';
export const GET_SUPPLIER_SUCCESS = 'GET_SUPPLIER_SUCCESS';
export const GET_SUPPLIER_FAILURE = 'GET_SUPPLIER_FAILURE';

export const SUPPLIER_EDIT_REQUEST = 'SUPPLIER_EDIT_REQUEST';
export const SUPPLIER_EDIT_SUCCESS = 'SUPPLIER_EDIT_SUCCESS';
export const SUPPLIER_EDIT_FAILURE = 'SUPPLIER_EDIT_FAILURE';

export const SUPPLIER_LOGOUT_REQUEST = 'SUPPLIER_LOGOUT_REQUEST';
export const SUPPLIER_LOGOUT_SUCCESS = 'SUPPLIER_LOGOUT_SUCCESS';
export const SUPPLIER_LOGOUT_FAIL = 'SUPPLIER_LOGOUT_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';